### ISSUE TITLE
Nothing happens if you don't already have a file opened in the editor when creating a new file

### ISSUE THREAD

**Issue by tofagerl** [dkundel/vscode-new-file#9]
If you launch vscode in a directory, and don't open any files, but just use cmd-alt-n to create a new file, it won't work.
If you first select an existing file, and then repeat the cmd-alt-n and try again to create the same file, it will work.
If you then delete the file you just created and close the first file you opened, you're back to not being able to create files.

I assume this has something to do with the code which determines which folder you want to create the file in, because that seems logical...

**Comment by dkundel** [comment]
Yeah that's a bug I realized yesterday as well. It's related to a change in that I recently did. I'll try to fix it this week and push a new update :) thanks for filing the issue!

**Comment by tofagerl** [comment]
Thanks for quick reply 👍

**Comment by masaeedu** [comment]
@dkundel Any luck with this? I tried taking a look in the code but I feel I don't really understand what's going. E.g. in `determineFullPath`, what is the following code trying to do?

    if (filePath.indexOf('/') === '/') {
      if (root) {
        deferred.resolve(path.join(root, filePath));
      } else {
        deferred.resolve(filePath);
      }  
      return deferred.promise;
    }

`indexOf` always returns an integer, so I don't think this branch is ever entered. 

I think it might be simpler to just suggest the typed filename/filepath relative to:

1. The containing folder of the currently open file (if available)
2. The workspace (if available)
3. The user's home folder

That way the user can simply choose which one they actually want (if it's the default, they just need to hit return). Here's what the workflow looks like in each case:

- [With no folder or file opened](https://onedrive.live.com/?authkey=%21AJYldYtyeOJ46pE&cid=C48EA5028DCDA65E&id=C48EA5028DCDA65E%213417&parId=root&o=OneUp)
- [With a folder opened, but no file in the editor](https://onedrive.live.com/?authkey=%21AJQRoVm6_GR2XJU&cid=C48EA5028DCDA65E&id=C48EA5028DCDA65E%213418&parId=root&o=OneUp)
- [With an active file in the editor](https://onedrive.live.com/?authkey=%21AEvBRUq7Fqi6QdI&cid=C48EA5028DCDA65E&id=C48EA5028DCDA65E%213419&parId=root&o=OneUp)

If this makes sense to you I can submit a PR.

**Comment by ilog2000** [comment]
Any news on this annoying issue?

**Comment by dkundel** [comment]
This should be fixed now with `v2.0.0` 😊

Sorry for the delay!

**Comment by ilog2000** [comment]
Sorry, it does not work for me even with v2.0.0. My steps to reproduce:

0. My location is c:\Users\<userName>\Downloads\
1. Execute "code.exe ." (note the spot - I am running VSCode on folder)
2. See VSCode background with some keymappings, press Ctrl+Alt+N
3. Enter "test.txt" and press ENTER button
4. See that nothing happens - neither window opens, nor file creates

**Comment by dkundel** [comment]
Hi @ilog2000!

That is because the default option is that it tries to use the current file path as "root" for the file created. You can change this behavior globally by changing the setting `"newfile.relativeTo": "project"` which will always create the files relative to the project structure. Make sure to look also into the other options. I chose `"file"` as the default option because that was the behavior of the original version of the extension.

**Comment by ilog2000** [comment]
Hi @dkundel

Thank you for the tip - now I see these options in the readme file. I will try to switch to "project" and see. But I have concerns about such approach - is it really needed? My understanding, that we either have a path to the particular file (then we can extract a directory to navigate from) or we have a project directory. And it's possible to make selection automatically, w/o choosing a suitable option in settings. Am I wrong?

**Comment by dkundel** [comment]
I'll be adding that behavior back as soon as I get around it. The reason why I introduced the other configuration is that there were other issues where people asked if the path could be an absolute path, if it could be relative to the project, if it could be relative to the current file and many more. So I tried to make everyone happy by offering the configuration. As part of that the fallback logic for "file" kinda dropped out again without me realizing it.

**Comment by dkundel** [comment]
Alright I published a new minor version that should fix this issue. Let me know if you hit any more issues :)

**Comment by ilog2000** [comment]
Thank you for this quick update. Unfortunately, it still doesn't work for me - neither with "file", nor with "project"/"root" (I was overriding only "newFile.relativeTo"). I tried to create "test.txt", then ".\test.txt", then "temp\test.txt", then ".\temp\test.txt" - nothing happened when all previously edited files are closed. I also re-installed addon several times.

**Comment by dkundel** [comment]
This is really odd. Which version of VS Code do you have installed? It works flawlessly for me. Can you very that it's really using the correct path by adding in your settings: `"newFile.showFullPath": true` to make the whole path visible. Maybe there is a Windows problem?

**Comment by ilog2000** [comment]
Oh, seems I finally found it. That "newFile.showFullPath": true was the initial setting. When I changed it to false, all started working as I expected. So, in my previous tests I was getting absolute path after pressing Ctrl+Alt+N, then I was replacing it with relative path, and there was no window created.

Thank you for help.

**Comment by dkundel** [comment]
Ah okay. Yeah another person had the same issue. It's hard to cater to all requests people have. Glad it works now though!
